config/routes.rb
Quizzer::Application.routes.draw do
  resources :quizzes
  resources :questions, :except => :index
  resources :answers , :except => :index
  resources :evaluations, :except => [ :index, :destroy ] do
    member do
      get 'pose_question', :as => 'pose_question_for'
      post 'compare_answers', :as => 'compare_answers_for'
    end
  end
  get 'about', :to => 'application#about'

  root :to => 'quizzes#index'

end

app/models/evaluation.rb
class Evaluation < ActiveRecord::Base
  belongs_to :quiz
  belongs_to :parent, :class_name => "Evaluation"
  has_many :results, :dependent => :destroy, :inverse_of => :evaluation
  accepts_nested_attributes_for :results

  attr_accessible :quiz_id, :parent_id, :completed, :results_attributes
  attr_readonly :quiz_id, :parent_id

  validates :quiz_id, :presence => true
  validates :completed, :inclusion => { :in => [ true, false ] }

  def question(id)
    quiz.questions.find(id)
  end

  def add_result(question_id, result)
    results.create! :question_id => question_id, :result => result
  end

  def question_ids
    (parent ? parent.results.incorrect.collect(&:question_id) : quiz.questions.collect(&:id)) - results.collect(&:question_id)
  end

  def randomized_question_ids
    question_ids.shuffle
  end
end

app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController
  before_filter :require_xhr, :only => [ :pose_question, :compare_answers ]

  def show
    @evaluation = Evaluation.find(params[:id])
  end

  def new
    @evaluation = Evaluation.new(params[:evaluation])
  end

  def create
    evaluation = Evaluation.new(params[:evaluation])
    if evaluation.save
      redirect_to edit_evaluation_url(evaluation)
    else
      redirect_to root_url
    end
  end

  def edit
    @evaluation = Evaluation.find(params[:id], :include => { :quiz => :questions })
    @question_ids = @evaluation.randomized_question_ids
  end

  def update
    evaluation = Evaluation.find(params[:id])
    evaluation.update_attributes!(params[:evaluation])
    if request.xhr?
      render :nothing => true
    else
      redirect_to evaluation
    end
  end

  def pose_question
    @evaluation = Evaluation.find(params[:id])
    @question = @evaluation.quiz.questions.find(params[:question_id])
  end

  def compare_answers
    @evaluation = Evaluation.find(params[:id])
    @question = @evaluation.question(params[:question_id])

    if @question.correct_answers? *params[:answers].values
      @evaluation.add_result @question.id, "correct"
      @partial = 'matched_answers'
    else
      @partial = 'mismatched_answers'
    end
  end
end

app/helpers/evaluations_helper.rb
module EvaluationsHelper
  def evaluation_answer_delimiter answer_count, i
    "<div class=\"delimiter #{ answer_count == 1 ? "non_numeric" : "numeric" }\">#{ answer_count == 1 ? answer_delimiter : i.to_s + '.' }</div>".html_safe
  end
end

app/views/evaluations/_matched_answers.html.haml
.correct_answers.correct_result{:style => 'display: none'}
  Correct!

.result_actions{:style => 'display: none'}
  .correct
    = submit_tag "Next Question"

app/views/evaluations/_mismatched_answers.html.haml
- answer_count = question.answers.count

.correct_answers{:style => 'display: none'}
  .header
    Correct #{pluralize_based_on_count "Answer", answer_count}:
  - question.answers.each_with_index do |answer, i|
    = evaluation_answer_delimiter(answer_count, i+1)
    .answer<
      = answer.text

.result_actions{:'data-action' => evaluation_path(@evaluation), :style => 'display: none'}
  .incorrect
    = submit_tag "OK, Next Question!", 'data-result' => 'incorrect'
  .correct
    = submit_tag "Actually, I Was Right!", 'data-result' => 'correct'
  .ignore
    = submit_tag "Ignore This Question!", 'data-result' => 'ignored'

app/views/evaluations/_posed_question.html.haml
- answer_count = question.answers.count

.question<
  = question.text

.answers_form{:answer_count => question.answers.count}
  = form_tag compare_answers_for_evaluation_path(@evaluation), :method => :post, :remote => true do
    .header
      Your #{pluralize_based_on_count "Answer", answer_count}:
    - answer_count.times do |i|
      = evaluation_answer_delimiter(answer_count, i+1)
      = text_field_tag "answers[#{i}]", nil, :size => 50, :maxlength => 50
      = hidden_field_tag "question_id", question.id
    = submit_tag "Submit"

.final_answers{:style => 'display: none'}
  .header
    Your #{pluralize_based_on_count "Answer", answer_count}:
  - answer_count.times do |i|
    = evaluation_answer_delimiter(answer_count, i+1)
    .answer{:class => "answer_#{i}"}
      
.result{:style => 'display: none' }

app/views/evaluations/compare_answers.js.erb
$eval = $('#evaluation_in_progress');
var answersCount = $eval.find('.answers_form').attr('answer_count');

/* transfer answers to final_answers div */
for(var i=0; i<answersCount; i++) {
  var value = $eval.find('.posed_question #answers_' + i).attr('value');
  if (typeof value === 'undefined' || value === false || value === "") {
    value = "&lt;none&gt;";
  }
  $eval.find('.final_answers .answer_' + i).html(value);
}

$eval
  .find('.posed_question .answers_form')
  .remove();

$eval
  .find('.final_answers')
    .show()
  .end()
  .find('.posed_question .result')
    .replaceWith('<%= escape_javascript render(@partial, :evaluation => @evaluation, :question => @question) %>');
    
$eval
  .find('.correct_answers,.result_actions')
  .fadeIn(300);

app/views/evaluations/edit.html.haml
- content_for :javascript do
  = javascript_include_tag 'evaluate'

#evaluation_in_progress{:'data-question-ids' => @question_ids.to_json, :'data-action' => evaluation_path(@evaluation)}
  .quiz_name
    = @evaluation.quiz.name

  .question_indicator
    Question
    %span.question_index
      1
    out of
    = @question_ids.size

  .posed_question{:'data-action' => pose_question_for_evaluation_path(@evaluation)}

  -# form is hidden from user and submitted by evaluate.js when no more questions are left
  .evaluation_complete
    = form_for @evaluation do |f|
      = f.hidden_field :completed, :value => true

app/views/evaluations/new.html.haml
#new_evaluation
  #instructions
    %p
      All quizzes are intended as learning aids only.
    
    %p
      If your answer to a quiz question is not an exact match, you will be shown
      the accepted answer to the question. If you feel your answer was correct,
      you have the option of indicating such. The quiz is for your benefit, so
      you are the ultimate judge. You can also choose to ignore the question. Correctly
      answered and ignored questions will not be represented if you retake the quiz.

    %p
      Many questions are code snippets, in which case the answer is the value
      returned by the presented code.

    %p
      Throughout the quiz, the following notation will be used:

    %p
      %span.code<
        ModuleName#method_name
      &mdash; instance method

    %p
      %span.code<
        ModuleName.method_name
      &mdash; class method

  = form_for @evaluation do |f|
    = f.hidden_field :quiz_id, :value => @evaluation.quiz_id
    = f.hidden_field :parent_id, :value => @evaluation.parent_id
    = f.submit "Start the Quiz Now!"

app/views/evaluations/pose_question.js.erb
$('#evaluation_in_progress')
  .find('.posed_question')
    .hide()
    .html('<%= escape_javascript render('posed_question', :question => @question) %>')
    .fadeIn(300)
  .end()
  .find('.question_index')
    .html(questionIndex.toString());
    
questionIndex += 1;

app/views/evaluations/show.html.haml
- correct_count = @evaluation.results.correct.count
- incorrect_count = @evaluation.results.incorrect.count
- total_count = correct_count + incorrect_count
- ignored_count = @evaluation.results.ignored.count

#evaluation_results
  .quiz_name
    = @evaluation.quiz.name

  .header
    Your Results:

  .results
    %p
      You got #{correct_count} out of #{total_count} #{pluralize_based_on_count "question", total_count} right!
    %p
      You ignored #{ignored_count} #{pluralize_based_on_count "question", ignored_count}.

  .standard_linkset
    - if incorrect_count > 0
      = link_to "Retake the questions you missed!", new_evaluation_path(:evaluation => { :parent_id => @evaluation.id, :quiz_id => @evaluation.quiz.id })
      = link_delimiter
    = link_to "Retake all the questions!", new_evaluation_path(:evaluation => { :quiz_id => @evaluation.quiz.id })
    = link_delimiter
    = link_to "Take a different quiz!", quizzes_path